### ISSUE TITLE
Create Pull Request Template

### ISSUE THREAD

**Issue by sperezm97** [DevsDO/whocode-frontend#9]

**Comment by sperezm97** [comment]
Este es el estandar que encontre para proyectos open source: 
https://github.com/stevemao/github-issue-templates/blob/master/bugs-only/PULL_REQUEST_TEMPLATE.md

**Comment by mecm1993** [comment]
@sperezm97 puedo ayudar con esto

**Comment by sperezm97** [comment]
@mecm1993  Te lo asignare, ando medio cortito de time
